- src/impl/metadata/retriever/baseMetadataRetriever.ts
- src/impl/metadata/retriever/profileRetriever.ts
- src/impl/source/profiles/profileActions.ts
Temporary Fix for #133 , API version set to 46.0 as tooling api has breaking changes in pulling entity definitions retrival @genoud  please note
> Temporay fix for reconcile

- messages/valid.json
- resources/metadata.json
- src/commands/sfpowerkit/package/valid.ts
Resolves Issue #195 
* Update the metadata JSON to API version 48
* Add optional metadata version flag to the package:valid command
* If no version is specified, the default 'metadata.json' is used for validation.
> Update metadata JSON to API version 48 

- messages/source_pmd.json
- src/commands/sfpowerkit/source/pmd.ts
Solves issue #197 
- Check whether pmd_cache_directory already exists before creating directory. This
resolves the error that was preventing multiple PMD release versions from being
cached.
- Add console log that informs the user which PMD release version is running.
> Update default PMD version to 6.21.0

- README.md
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/source/apextestsuite/convert.ts
- yarn.lock
Apex Test Suite convert only worked in a specific scenario with the file paths mentioned in packageDir/main/default/apextestsuite, Any change will render the function to throw an error.
This fix is to utilize a glob to check the entire repository for the file and then process it.
> Fix Apex Test Suite

- src/commands/sfpowerkit/org/connectedapp/retrieve.ts
fix: Corrected casing when converting flag apiversion to retrieverequest apiVersion
> fix: Corrected flag apiversion casing

- src/commands/sfpowerkit/org/destruct.ts
parsing the error message and printing in console.
issue #240
> fix: error messaging on sfdx:org:destruct failure

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/package/valid.ts
- src/commands/sfpowerkit/pool/delete.ts
- src/commands/sfpowerkit/pool/fetch.ts
- src/impl/pool/scratchorg/poolCreateImpl.ts
- src/impl/project/diff/diffUtil.ts
- yarn.lock
ScratchOrgs are only committed to the pool only after only scripts are completed across all the scratchorgs. This fix  is to bring
the commit early, so any scratchorg that is finished execution will be committed to the pool immediately.
The logs for execution of scripts in individual scratch org's will be stored in script_exec_outputs folder
> fix: commit scratchorgs to pool early

- README.md
- azure-pipelines.yaml
- templates/build-template.yml
- templates/smoke-test-template.yml
- sfpowerscripts is not supported on Mac, Install Manually
- Pass platform parameter to the pipeline
- Set Continue on error for Publish
> Fix Pipeline Failure on MacOs and other fixes

- package.json
- src/impl/pool/scratchorg/poolCreateImpl.ts
Scratch Org logging are written to script_exec_outputs. It was
incorrectly deleted during every execution of queue. This fixes the
incorrect clearing
> Fix missing log files  in Scratch Org create command

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/package/dependencies/install.ts
Add retry capability while fetching the installed packages in an org. This query can be awfully slow, especially in a new scratchorg for some unknown reason, causing pipelines to fail. Hence add a retry and skip if still not able to figure out  the packages.
> Add retry capability to fetch installed packages in an org

- README.md
- messages/scratchorg_pool_create.json
- npm-shrinkwrap.json
- oclif.manifest.json
- schemas/pool/so_pool_config_tag_mode.json
- src/commands/sfpowerkit/pool/create.ts
- src/impl/pool/scratchorg/poolCreateImpl.ts
- Support for Batch Size
Batch Size of the pool creation is now configurable by basis of an additional flag, rather than the hardcoded value of 10
- Support for relaxing all ip ranges
The schema now supports an addition relax_all_ip_ranges, which can relax all ip ranges in the created scratch org, mainly for non CI users
- Fixes to Logging
Streamlined logging, now there would be no script execution log in the console output. All scripts logs will be written directly the log files
- Bugfix Deletion of ScratchOrg
ScratchOrg that had script execution failures where not returned to the pool.
> Enhancements to Scratch Org Pool

- README.md
- messages/dependency_versionlist.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/package/dependencies/list.ts
- src/commands/sfpowerkit/package/dependencies/versionlist.ts
Often when working with packages, it is quite common to use .next to aid in package versions. However it is hard to understand, against which dependency this package was created ( unless you have a real strong versioning strategy in play). This command resolves next to the exact version of the dependent packages and updates the .sfdx project json. 
This solves the issues as logged in https://github.com/forcedotcom/cli/issues/593
> feat: Dependency version list feature

- src/commands/sfpowerkit/source/apextest/list.ts
- src/impl/parser/ApexTypeFetcher.ts
This is a fix for an issue @aly76 mentioned at https://github.com/nawforce/apex-parser/issues/3. 
The problem you are having is that Apex being a case insensitive language needs to use a special input stream for ANTLR. In the PR I have swapped the input stream and removed the workarounds. I have tested the this against a few thousand Apex files without error. 
While I was testing I had a problem with the fs.existsSync call in list.ts, fs was undefined. I tweaked the code to workaround this but not really sure what my problem was so you may not want that change.
> Use CaseInsensitiveInputStream for Apex parsing

- src/commands/sfpowerkit/org/manifest/build.ts
- src/impl/metadata/packageBuilder.ts
Quick Filters were excluding all metadata due to incorrectly applied filtering. Needed to correctly manage exclusion rules.
Added an exclusion at the per-member level so you could exclude an individual member, using the `type:membername` pattern used elsewhere in SFDX and not just an entire type, `force:source:deploy -m` as an example of specific member reference style.
> Make org:manifest:build --quickFilter function correctly

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/pool/scratchorg/poolCreateImpl.ts
When scratch orgs fail due to an error in the poooling script,
logs are not written to the logfile.
Fixed by moving the stderror stream out from the call back
Fixes #385
> Fix Error Logs not written while creating ScratchOrg Pools

- messages/source_pmd.json
- resources/pmd-ruleset.xml
- src/commands/sfpowerkit/source/pmd.ts
The default PMD version is now 6.34.0.
The deprecated rules have been removed from
`pmd-ruleset.xml` and have been replaced by
the new rules equivalent.
> update PMD to version 6.34.0.

- messages/scratchorg_poolFetch.json
- npm-shrinkwrap.json
- src/commands/sfpowerkit/pool/fetch.ts
- src/impl/pool/scratchorg/poolCreateImpl.ts
- src/impl/pool/scratchorg/poolFetchImpl.ts
- src/utils/scratchOrgUtils.ts
- src_saleforce_packages/scratchorgpool/force-app/main/default/objects/ScratchOrgInfo/fields/SfdxAuthUrl__c.field-meta.xml
This PR goal is to automatically authorize a user running `sfdx sfpowerkit:pool:fetch`, without him having to manually login to the Org.
To do this, we need the Sfdx Auth Url for the Scratch Org.
As Sfdx Auth Url is not returned when the user creating the Scratch Org has login to the DevHub via JWT, this will only be available if the user has login via `sfdx force:auth:sfdxurl:store`. DevHub Auth Url could be saved as a secret in the repo.
This PR has several parts:
* Add a field to store the Sfdx Auth Url on `ScratchOrgInfo` in the `sfpower-scratchorg-pool` Unlocked package
* Update the `sfdx sfpowerkit:pool:create` to save the Sfdx Auth Url if available
* Update the `sfdx sfpowerkit:pool:fetch` to automatically authorize a user if the Sfdx Auth Url is available for the Scratch Org
> Automatically authorize a user fetching an org from a pool

- src/commands/sfpowerkit/pool/fetch.ts
- src/impl/pool/scratchorg/poolFetchImpl.ts
- Skip login to scratch orgs created using a Dev Hub authenticated with JWT, when fetching from scratch org pool 
- AuthInfo.getSfdxAuthUrl() does not return a valid Sfdx Auth URL for a scratch org created using a Dev Hub authenticated using JWT. The refreshToken is undefined and the clientId is incorrect.
- The login attempt is skipped when the Sfdx Auth URL is invalid
> Skip login to scratch org created with JWT auth

- src/impl/metadata/retriever/metadataRetriever.ts
Happen when only one record returned for metadatatype.
> fix:IIssue #524 Profile reconcile

- src/commands/sfpowerkit/package/dependencies/install.ts
Fix an unhandled exception when a dependent package is not found in packageAliases and provide meaningful error message to guide the users
﻿
> Bug: Unhandled error when package is missing in packageAliases during dependency installation

- src/commands/sfpowerkit/package/dependencies/install.ts
Packages in the same repo can be added as a dependency to another package, and it should be skipped as source
code of these packages are available. A bug was causing all the packages to be installed if there was no existing packages in the scratch org
> Bug: Packages in  mono repo getting installed

- src/utils/scratchOrgUtils.ts
Removing break preventing all fields from being assessed.
> Fixes #535

- src/utils/scratchOrgUtils.ts
Fix #542
Scratch Orgs created from a DevHub using JWT bearer token doesnt have authURL. This was not enforced 
in the previsous version of salesforce-core lib. 
This will allow pools to be created, but will show an info message.﻿
> Fix for Scratch Orgs Not created with JWT Bearer Flow

- src/impl/parser/listeners/ApexTypeListener.ts
Fix identification of test classes with parameters in @istest annotation, by
performing string search on entire context instead of _stop.
Fix #546
> Fix test class identification

- templates/smoke-test-template.yml
Smoke tests have been repeatedly failing when pull requests are raised.  
I looked into azure devOps to inspect the error and found this.
Updated the authentication to AuthURL
> Added sfdx authURL authentication to smoke test pipeline

- src/commands/sfpowerkit/org/matchingrule/activate.ts
- src/commands/sfpowerkit/org/matchingrule/deactivate.ts
There is a strange quirk with managed MatchingRules where Salesforce will retrieve the metadata with the namespace, but they must be deployed without the namespace. This should resolve that by removing the namespace from the matching rule.
> Fix namespace issue with MatchingRules

- package.json
Dependency on glob was missing after npm-shrinkwrap was deleted in #572
> Install dependency glob 

- src/commands/sfpowerkit/package/valid.ts
- Fix broken bypass functionality in `package:valid` command
- Breaking change in schema of JSON output.
Closes #607
> fix(package-valid)!: bypass flag not respected

- README.md
the xml link is out of the window.
user must scroll to the right to see the full content.
this commit improves readibility.
> Fixed new line text in sfpowerkit:org:destruct section

- README.md
README.md documentation was missing the -a flag for `sfdx sfpowerkit:pool:fetch`.
Added -a flag and description to the README.md file.
closes #612
> Added -a flag to fetch command in README.md file

- README.md
Removed as apextest:list is no longer in beta in the documentation.
> Remove 'beta' from readme for sfpowerkit:source:apextest:list

- README.md
Link to source and visible path for sfpowerkit:source:profile:{retrieve,reconcile} were broken.
> Fixed path/link for profile retrieve and reconcile

- package.json
- src/sfpowerkit.ts
- src/utils/sfpLogger.ts
This PR is to remove the dependency on pino and use simpler SFPLogger, ensuring its playing in nicely with progress bars etc.﻿
> fix(logs): remove pino to use simpler sfplogger, as this is not mixing nicely with progrss bars

- src/impl/project/diff/diffImpl.ts
Refactor to use lastest version of simple-git, moving away from promises
> refactor(diff): use simple-git directly as opposed to simple-git/promise, as its deprecated
