- README.md
> [ci skip] update readme

- src/commands/sfpowerkit/source/picklist/generatepatch.ts
- src/shared/getSafe.ts
Fixes [AB#51](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/51)
> Ignore Standard Value set controlling fields

- README.md
- messages/source_picklist_generatepatch.json
- src/commands/sfpowerkit/source/picklist/generatepatch.ts
Fixes [AB#47](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/47)
> Added flag, readme

- src/commands/sfpowerkit/source/picklist/generatepatch.ts
> Removed dummy value

- src/commands/sfpowerkit/org/connectedapp/retrieve.ts
- src/shared/checkRetrievalStatus.ts
Hotfix to release branch cherrypicked for master
Fix for Json log in retrieval command
> Fix to retrieve command to disable logs if json flag

- src/commands/sfpowerkit/source/picklist/generatepatch.ts
Fix for [AB#56](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/56)
> Hotfix for generate patch

- README.md
- messages/profile_reconcile.json
- messages/source_profile_generate.json
- npm-shrinkwrap.json
- package.json
- src/commands/sfpowerkit/source/profile/reconcile.ts
- src/commands/sfpowerkit/source/profile/retrieve.ts
- src/impl/metadata/retriever/apexClassRetriever.ts
- src/impl/metadata/retriever/apexPageRetriever.ts
- src/impl/metadata/retriever/customApplicationRetriever.ts
- src/impl/metadata/retriever/entityDefinitionRetriever.ts
- src/impl/metadata/retriever/fieldRetriever.ts
- src/impl/metadata/retriever/layoutRetriever.ts
- src/impl/metadata/retriever/profileRetriever.ts
- src/impl/metadata/retriever/recordTypeRetriever.ts
- src/impl/metadata/retriever/tabDefinitionRetriever.ts
- src/impl/source/profiles/profileActions.ts
- src/impl/source/profiles/profileReconcile.ts
- src/shared/metadataFiles.ts
Add support on static reconcile. reconcile again components in the
project only
Fixes [AB#57](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/57)
> Profiles reconcile in destination folder

- README.md
- messages/profile_retrieve.json
- src/commands/sfpowerkit/source/profile/merge.ts
- src/commands/sfpowerkit/source/profile/reconcile.ts
- src/commands/sfpowerkit/source/profile/retrieve.ts
- src/impl/source/profiles/profileActions.ts
- src/impl/source/profiles/profileMerge.ts
- src/impl/source/profiles/profileSync.ts
- src/sfpowerkit.ts
Avoid retrieve profile not in the folder path provided.
Fix [AB#65](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/65)
> Fix Profile retrieve and Merge: Respect folder path

- src/impl/source/profiles/profileReconcile.ts
- src/sfpowerkit.ts
Fix [AB#71](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/71)
> Fix reconcile appVisibility

- README.md
- messages/source_picklist_generatepatch.json
- messages/valid.json
- oclif.manifest.json
- src/commands/sfpowerkit/package/valid.ts
- src/commands/sfpowerkit/source/picklist/generatepatch.ts
added enhancement to move the standardvalueset from package to patch.
ISSUE [AB#75](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/75)
> ISSUE 75 generate picklist enhancement

- README.md
- messages/package_build.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/org/manifest/build.ts
- src/impl/metadata/packageBuilder.ts
Integrated plugin sfdx-build (https://www.npmjs.com/package/sfdx-build) into sfpowerkit with minor changes
> Feature 74 Build manifest file

- src/impl/metadata/metadataFiles.ts
- src/impl/project/diff/diffImpl.ts
- src/impl/project/diff/diffUtil.ts
Enforce respect of .forceignore when building building diff
> Fix diff command when output folder point on a parent folder

- src/commands/sfpowerkit/package/valid.ts
> Check for Array if there is only one element

- npm-shrinkwrap.json
- src/impl/metadata/metadataFiles.ts
- src/impl/project/diff/diffImpl.ts
- src/impl/project/diff/diffUtil.ts
- src/sfpowerkit.ts
Copy .forceignore and sfdx-project.json. check existence before Copy
Copy of folder stating with . (.circleci for example)
permissionSet management:
Incremental deployment in API 39 and earlier
Full deployment in API 40 and later
> Fix Diff Command issue #104

- src/impl/source/profiles/profileMerge.ts
This is a proposed solution for issue #112
> Fix for issue #112

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/project/diff.ts
- src/impl/project/diff/diffImpl.ts
Debug statements for [AB#85](https://dev.azure.com/cloudfirstanz/f7a91473-0e1c-490e-b0a0-80f9f8d82c14/_workitems/edit/85)
> Added debug flag to diff commands

- README.md
Updated readme markdown for instructions to install via CI process or the like.
> Updating Readme Markdown

- README.md
Fix #140  Removed Markdown for Azure Boards
> Removed Azure Markdown

- src/commands/sfpowerkit/org/matchingrule/deactivate.ts
> Fix #149 Deactivate Commands

- src/commands/sfpowerkit/source/permissionset/generatepatch.ts
- src/commands/sfpowerkit/source/picklist/generatepatch.ts
- src/sfpowerkit.ts
> #158 Fix improper loging variable

- README.md
- messages/project_diff.json
- npm-shrinkwrap.json
- package.json
- src/commands/sfpowerkit/project/diff.ts
- src/impl/project/diff/customLabelsDiff.ts
- src/impl/project/diff/diffImpl.ts
- src/impl/project/diff/sharingRuleDiff.ts
- src/impl/project/diff/workflowDiff.ts
> Issue #157: Generate destructiveChanges.xml provided a flag is set

- src/impl/metadata/metadataInfo.ts
- src/impl/metadata/retriever/customPermissionRetriever.ts
- src/impl/metadata/retriever/entityDefinitionRetriever.ts
- src/impl/metadata/retriever/externalDataSourceRetriever.ts
- src/impl/metadata/retriever/flowRetriever.ts
- src/impl/metadata/schema.ts
- src/impl/source/profiles/profileMerge.ts
- src/impl/source/profiles/profileReconcile.ts
Also add
- support for merge externalDatasSources
- support for merge CustomPermissionsm ExternalDataSources
> Issue #147 Add support for customMetadataTypeAccesses and flowAccesses

- messages/source_permissionset_generatepatch.json
- src/commands/sfpowerkit/source/permissionset/generatepatch.ts
- src/impl/metadata/metadataFiles.ts
respect of .forceignore file
set default loglevl to info
use sfpowerkit.log for loging
> Issue #124

- src/impl/project/diff/diffImpl.ts
Generate destructiveChanges.xml when unsplited metadata are delete and no other metadata component is deleted.
> Issue #166

- src/commands/sfpowerkit/auth/login.ts
> Fix Alias for login

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/project/diff/diffImpl.ts
- src/utils/dxProjectManifestUtils.ts
- yarn.lock
Fix for issue #178  Please review
> Fix #178, Clean Sfdx-project.json after diff

- src/commands/sfpowerkit/source/profile/merge.ts
- src/commands/sfpowerkit/source/profile/reconcile.ts
- src/commands/sfpowerkit/source/profile/retrieve.ts
- src/impl/metadata/builder/userPermissionBuilder.ts
- src/impl/metadata/metadataFiles.ts
- src/impl/metadata/retriever/apexClassRetriever.ts
- src/impl/metadata/retriever/apexPageRetriever.ts
- src/impl/metadata/retriever/customApplicationRetriever.ts
- src/impl/metadata/retriever/customPermissionRetriever.ts
- src/impl/metadata/retriever/entityDefinitionRetriever.ts
- src/impl/metadata/retriever/externalDataSourceRetriever.ts
- src/impl/metadata/retriever/fieldRetriever.ts
- src/impl/metadata/retriever/flowRetriever.ts
- src/impl/metadata/retriever/layoutRetriever.ts
- src/impl/metadata/retriever/profileRetriever.ts
- src/impl/metadata/retriever/recordTypeRetriever.ts
- src/impl/metadata/retriever/tabDefinitionRetriever.ts
- src/impl/metadata/retriever/userLicenseRetriever.ts
- src/impl/project/diff/diffImpl.ts
- src/impl/project/diff/diffUtil.ts
- src/impl/project/diff/permsetDiff.ts
- src/impl/project/diff/profileDiff.ts
- src/impl/source/profiles/profileMerge.ts
- src/impl/source/profiles/profileReconcile.ts
- src/impl/source/profiles/profileSync.ts
- src/utils/extract.ts
Fix issue with diff command
Refactor lodash lib importation
> Issue #185 Diff not copying files with space

- README.md
- messages/project_diff.json
- src/commands/sfpowerkit/project/diff.ts
- src/impl/project/diff/diffImpl.ts
- src/sfpowerkit.ts
Add experimental flags to do the following
- Bypass certain directories while doing diff
- Generate diff only for certain folders and create a sfdx-project.json targeting the mentioned path
> adding ignore option to project diff

- src/impl/metadata/schema.ts
- src/impl/project/diff/profileDiff.ts
Support customMetadataTypeAccesses, customSettingAccesses and
flowAccesses
Remove full name from generated profile is value is empty.
> Issue #191 Support to new profiles fields in diff

- src/impl/metadata/metadataFiles.ts
Display Lightning Event, Interface and App in the diff output
> Issue #196 Display Other Aura Components elements

- src/impl/source/profiles/profileMerge.ts
- src/impl/source/profiles/profileReconcile.ts
Profile Merge
PRofile reconcile
> Add support of CustomSettingAccess

- README.md
- messages/org_coverage.json
- src/commands/sfpowerkit/org/orgcoverage.ts
issue #217
exposting test result in csv or json format
> issue #217

- messages/project_orgdiff.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- resources/metadatainfo.json
- src/commands/sfpowerkit/project/orgdiff.ts
- src/impl/project/orgdiff/orgDiffImpl.ts
> medata info for entitlementProcess,milestoneType,fieldTranslation

- src/commands/sfpowerkit/source/apextestsuite/convert.ts
check if the testclass is array or string then handle both scenarion
> fixing test suite convert bug

- src/commands/sfpowerkit/source/profile/reconcile.ts
Catch error when running profice reconcile and retry.
> Issue #242

- src/commands/sfpowerkit/source/pmd.ts
> Update default PMD version to 6.22.0

- src/impl/project/diff/diffImpl.ts
Making the command run when the project is created
as a subfolder in a repository.
Solve Issue #251
> fix: Command run from subfolder

- src/commands/sfpowerkit/source/profile/reconcile.ts
- src/impl/metadata/retriever/baseMetadataRetriever.ts
- src/impl/metadata/retriever/entityDefinitionRetriever.ts
- src/impl/metadata/retriever/fieldRetriever.ts
- src/impl/metadata/retriever/layoutRetriever.ts
- src/impl/metadata/schema.ts
- src/sfpowerkit.ts
Use of standard query for EntityDefinition object instead of tooling
Use bulk API when recordCount greater that 2000
Show progress when querying data if log level flag is debug or trace.
Issue #256
> fix: Profile reconcile

- README.md
- oclif.manifest.json
- src/commands/sfpowerkit/package/version/codecoverage.ts
pkg coverage runs against prod. replace flag `u|targetusername` with `v|targetdevhubusername`.
issue #267
> fix: targetdevhubusername instead targetusername

- oclif.manifest.json
- tsconfig.json
> fix: incorrect tsconfig

- src/impl/pool/scratchorg/poolCreateImpl.ts
Removed an exception which caused scratch orgs pool to create an incorrect log message
> Removed erroneus exception

- README.md
> fix: udpate readme

- npm-shrinkwrap.json
- oclif.manifest.json
- src/commands/sfpowerkit/org/healthcheck.ts
- src/commands/sfpowerkit/org/orgcoverage.ts
- src/commands/sfpowerkit/org/sandbox/create.ts
- src/commands/sfpowerkit/org/sandbox/info.ts
- src/commands/sfpowerkit/org/sandbox/refresh.ts
- src/commands/sfpowerkit/org/scratchorg/delete.ts
- src/commands/sfpowerkit/org/scratchorg/usage.ts
- src/sfpowerkit.ts
- src/utils/scratchOrgUtils.ts
Pino for some reason  is causing the Logger to fail during linking. Switching to old require statement
> Switch Pino back to normal format, as its causing import errors

- src/commands/sfpowerkit/package/valid.ts
> fix: error handling and updates error messages

- README.md
- oclif.manifest.json
- src/commands/sfpowerkit/org/orgcoverage.ts
- src/impl/dependency/dependencyImpl.ts
- src/impl/metadata/retriever/metadataSummaryInfoFetcher.ts
#297 Adding package name to org test coverage result output
> enhancements to orgcoverage command to include package name in output

- azure-pipelines.yaml
- package.json
- templates/build-template.yml
- templates/smoke-test-template.yml
Introduce YAML version of Azure Pipelines for managing release
> Yaml pipelines

- templates/smoke-test-template.yml
The alias for org:coverage is  incorrect
> Update smoke test with correct alias

- package.json
- src/commands/sfpowerkit/package/dependencies/install.ts
resolve actual package version number in .LATEST scenario
order by buildnumber and createddate on Package2Version query
> fix: refactor install dependencies command

- messages/package_build.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/org/manifest/build.ts
- src/impl/metadata/packageBuilder.ts
Add child metadata in the package.xml.
> fix: Issue #279

- README.md
- messages/org_relaxiprange.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/org/relaxiprange.ts
- src/impl/org/relaxIPRangeImpl.ts
Issue #314  : Enhancement to set iprange as 0.0.0.0-255.255.255.255 in target org and remove any existing iprange in target org.
> feat: support for addall and removeall

- src/impl/package/version/packageInfo.ts
Fix error handling when unable to retrieve license info in org such as scratchorg
> Fix error handling

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/package/dependencies/install.ts
Add a null pointer check for a bug which cause package dependencies to fail in some scenarios
> Bugfix for null/undefiend in package:dependencies

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/metadata/metadataFiles.ts
- src/impl/project/diff/diffImpl.ts
- src/impl/project/diff/diffUtil.ts
- src/utils/fileutils.ts
- yarn.lock
Fix path sep issue.
Enfore windows and linux seprator for path.
> fix: ISSUE #339

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/metadata/retriever/entityDefinitionRetriever.ts
- yarn.lock
This fix the multiple API call when running reconcile.
> fix: Multiple API call in reconcile

- README.md
- messages/sandbox_create.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/org/sandbox/create.ts
- src/commands/sfpowerkit/org/sandbox/info.ts
- src/commands/sfpowerkit/org/sandbox/refresh.ts
> make licencetype mandatory if sandbox to be created from prod

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- resources/metadatainfo.json
- src/impl/metadata/metadataFiles.ts
- src/impl/metadata/metadataInfo.ts
- src/impl/project/diff/diffUtil.ts
- yarn.lock
Add Support of ExperienceBundle
> feat: Issue #383

- README.md
- messages/dependency_versionlist.json
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/package/dependencies/list.ts
- Remove version id written in sfdx-project.json
- Change flag to 'w' for write
- Update readme
> Remove versionid written in sfdx-project.json

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/source/picklist/generatepatch.ts
- src/impl/metadata/packageBuilder.ts
1. create nested folder for generate picklist patch incase folder structure is different to standard template
2. Ignore ManagedTopic in org manifest builde
> regression fix

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- resources/default-config.json
- resources/metadata.json
- resources/metadatainfo.json
- src/commands/sfpowerkit/source/pmd.ts
- src/utils/scratchOrgUtils.ts
- src_saleforce_packages/scratchorgpool/sfdx-project.json
- yarn.lock
https://mdcoverage.secure.force.com/services/apexrest/report?version=50
> update metadata coverage report and api version 50

- README.md
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/pool/delete.ts
- src/commands/sfpowerkit/pool/list.ts
set default loglevel to info for pool commands
> set default loglevel to info for pool commands

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/metadata/retriever/fieldRetriever.ts
Fix reconcile for Activity fields
> fix:Issue #446

- azure-pipelines-review.yaml
- azure-pipelines.yaml
- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- templates/smoke-test-template.yml
Increment version for pipeline fix
> Increment version

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/metadata/schema.ts
- src/impl/metadata/writer/profileWriter.ts
- src/impl/project/diff/profileDiff.ts
- src/impl/source/profiles/profileMerge.ts
- src/impl/source/profiles/profileReconcile.ts
Fix Diff and profile commands to take into considerations the loginFlow.
> fix:issue#460

- .vscode/extensions.json
- src/impl/metadata/builder/userPermissionBuilder.ts
- src/impl/metadata/retriever/metadataRetriever.ts
- src/impl/metadata/retriever/profileRetriever.ts
- src/impl/source/profiles/profileActions.ts
- src/impl/source/profiles/profileDiff.ts
- src/impl/source/profiles/profileMerge.ts
- src/impl/source/profiles/profileReconcile.ts
- src/impl/source/profiles/profileSync.ts
Improve code quality of profiles commands
- reconcile tabs while using retrieve to only fetch deployable tabs
> Refactor userPermissionBuilder

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/metadata/retriever/metadataRetriever.ts
Profile reconcile
Use FieldDefinition object for fields reconcile
USe Query on RecordType object for RecordType reconcile
to handle PersonAccount recordTypes.
> fix:Issue #469

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/user/password/generate.ts
- src/impl/pool/scratchorg/poolCreateImpl.ts
- src/impl/user/passwordgenerateimpl.ts
- src/utils/scratchOrgUtils.ts
> Refactor password generation and error handling for Pool creation

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/commands/sfpowerkit/package/dependencies/install.ts
- src/utils/get18DigitSalesforceId.ts
> convert 15 digit salesforce id to 18 digit salesforce id

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/source/profiles/profileReconcile.ts
> handle reconcileuserpermission on sourceonly mode

- npm-shrinkwrap.json
- oclif.manifest.json
- package.json
- src/impl/metadata/retriever/metadataRetriever.ts
Fix issue #500 
Check whether isPersonType field exists before running record type query
> Fix recordType query in metadataRetriever

- src/commands/sfpowerkit/pool/list.ts
- src/impl/pool/scratchorg/PoolDeleteImpl.ts
- src/impl/pool/scratchorg/poolFetchImpl.ts
- src/impl/pool/scratchorg/poolListImpl.ts
- src/utils/scratchOrgUtils.ts
> Fixing typo with pools

- package.json
- src/impl/parser/ApexTypeFetcher.ts
- src/impl/parser/listeners/ApexTypeListener.ts
Version 2.11.0 of the apex-parser contains support for UPDATE VIEWSTAT/TRACKING in SOQL
> chore(apex-parser): upgrade apex-parser dependency to 2.11.0

- src/impl/metadata/retriever/profileRetriever.ts
> fix:issue #596

- package.json
- resources/metadata.json
- src/commands/sfpowerkit/package/valid.ts
Package valid command is using sfdx node wrapper to convert to source format. The convert is
failing. Rather than fixing it, I have took the opportunity to use SDR to figure the component 
and filter based on it
fix #604
> fix(valid): fix Package:valid to use source-deploy-retrieve library

- src/commands/sfpowerkit/package/valid.ts
Fix naming of properties in SFDXPackage to be more accurate
> fix(package-valid)!: property name

- src/impl/metadata/retriever/metadataRetriever.ts
This is part 1 of the optimization as referred in #610.
Uses the underlying cache to lookup individual component rather than the full object﻿
> feature(reconcile): Use cache to lookup metadata 

- .eslintignore
- .eslintrc.js
- package.json
Add a basic eslint configuration for linting code﻿
> Add ESlint configurations

- src/impl/project/diff/diffImpl.ts
Add default to the first package when specific package
directories are provided to the command.
> fix:Issue #617

- src/impl/source/profiles/profileReconcile.ts
- src/impl/source/profiles/reconcileWorker.ts
reconcile crashes in source only mode, as it is de referencing target org
fix #637
> fix(reconcile): fix reconcile in source only mode

- src/commands/sfpowerkit/org/connectedapp/create.ts
- src/commands/sfpowerkit/org/destruct.ts
- src/commands/sfpowerkit/org/duplicaterule/activate.ts
- src/commands/sfpowerkit/org/duplicaterule/deactivate.ts
- src/commands/sfpowerkit/org/matchingrule/activate.ts
- src/commands/sfpowerkit/org/matchingrule/deactivate.ts
- src/commands/sfpowerkit/org/trigger/activate.ts
- src/commands/sfpowerkit/org/trigger/deactivate.ts
- src/commands/sfpowerkit/package/applypatch.ts
- src/commands/sfpowerkit/package/valid.ts
- src/commands/sfpowerkit/source/customlabel/create.ts
- src/impl/org/relaxIPRangeImpl.ts
- src/impl/pool/scratchorg/poolCreateImpl.ts
- src/impl/project/diff/diffUtil.ts
- src/impl/source/profiles/profileActions.ts
- src/utils/scratchOrgUtils.ts
https://github.com/Accenture/sfpowerkit/issues/642
checkForPreRequisite function in so SO pool using metadata api to check the field existence, which make the user requires metadata permission in production. so replacing the metadata.read with query on FieldDefinition.
> replace metadata.read with query on FieldDefinition

- src/commands/sfpowerkit/org/sandbox/refresh.ts
Fixes #625, Add description to sandbox refresh
> Fix for Issue #625 sandbox refresh

- src/commands/sfpowerkit/source/picklist/generatepatch.ts
removed white spaces picked up from codefactor
> removed white spaces from generatepatch.ts
